export const SUBMITTED_STATUS = 'SUBMITTED_STATUS';
export const TOUCHED_STATUS = 'TOUCHED_STATUS';
export const BLURRED_STATUS = 'BLURRED_STATUS';
export const SUBMITTING_STATUS = 'SUBMITTING_STATUS';
